# -*- coding: utf-8 -*-
"""graphcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcDvX1jFtwuqkjvGElT56qe84s0ECjn2
"""

# Lucas Malave — CSC-450 Final Figures (6 total) — 100% working version
# Paste this whole thing into a fresh Google Colab notebook and run

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats
import io

# Fixed CSV — every row now has exactly 27 columns
data = """Timestamp,Age,Current year in college,Major field of study,Overall GPA,Are you involved in any extracurricular activities?,If yes please specify which extracurriculars,1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,20.
11/13/2025 9:51:03,23,Senior,Computer Science,3.78,Yes,"Weightlifting club, church choir",4,1,1,5,1,4,5,3,1,3,1,5,5,1,5,5,1,4,5,5
11/13/2025 9:51:37,21,Senior,Computer Science,3.5,No,,5,3,2,4,3,2,3,1,1,4,3,4,3,3,4,4,4,4,3,2
11/13/2025 9:52:04,21,Senior,Computer Science,3.49,No,,5,3,2,4,2,3,4,3,3,4,2,3,3,3,4,4,4,2,5,3
11/13/2025 9:52:24,22,Senior,Computer Science,3.5,No,,4,3,3,3,3,3,4,4,3,2,3,4,3,4,3,4,4,2,4,2
11/13/2025 9:52:41,21,Senior,Computer Science,3.47,No,,4,4,4,2,5,4,3,2,1,2,5,5,4,4,2,2,5,3,5,4
11/13/2025 9:52:58,21,Senior,Computer Science,3,Yes,"Costume Theatre & Cosplay Club",4,4,4,5,5,4,5,4,4,4,5,5,4,4,5,5,5,3,4,3
11/13/2025 9:53:04,24,Senior,Computer Science,2.69,No,,4,4,4,2,1,4,5,3,1,2,3,2,4,3,3,4,2,4,3,1
11/13/2025 9:53:05,21,Senior,Computer Science,2.8,Yes,"Radio Club",4,4,4,3,4,4,5,3,4,3,5,3,4,3,3,3,5,3,5,3
11/13/2025 9:53:24,22,Senior,Computer Science,3.12,Yes,,4,5,2,4,3,5,3,5,2,4,4,3,5,5,2,5,4,2,1,1
11/13/2025 9:53:37,24,Senior,Computer Science,3.75,Yes,"Radio Show, Storytelling Club",5,5,1,5,5,2,4,5,4,5,5,5,2,5,5,5,2,5,5,1
11/13/2025 9:54:43,21,Senior,Computer Science,2.82,Yes,"Office admin & dog walker",3,3,4,5,5,4,3,4,3,5,5,5,5,4,5,4,5,5,5,5
11/13/2025 9:54:44,23,Senior,Computer Science,2.5,No,,4,5,4,4,4,3,5,4,3,4,3,4,3,4,3,4,4,5,5,4
11/13/2025 9:54:48,22,Senior,Computer Science,3.92,No,,4,4,5,2,3,4,4,3,1,2,2,5,5,4,3,2,5,3,3,4
11/13/2025 11:58:11,27,Senior,Computer Science,2.8,No,,4,2,2,4,2,2,3,3,2,3,3,3,2,3,3,3,3,3,3,1
12/3/2025 10:49:24,22,Senior,Health science,3.2,Yes,Baseball,5,3,2,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
12/3/2025 10:50:20,20,Sophomore,Psychology,3.62,Yes,Baseball,4,3,4,5,4,5,3,5,3,4,4,5,4,4,4,5,5,4,4,5
12/3/2025 10:50:36,19,Sophomore,psychology,2.9,Yes,"Baseball, intramurals",4,3,4,2,2,4,5,3,2,1,2,4,2,3,4,5,5,5,4,5
12/3/2025 10:50:50,20,Sophomore,Health science,3.3,Yes,"Baseball, investment club",4,4,3,3,3,3,4,3,2,4,2,4,4,4,3,4,2,3,4,5
12/3/2025 10:52:15,21,Senior,Health Science,3.65,Yes,Baseball,4,2,2,2,4,3,4,2,2,4,3,4,4,4,2,3,4,4,3,2
12/3/2025 10:52:46,20,Sophomore,Finance,3.5,Yes,Baseball,4,3,4,4,3,4,5,3,2,4,2,5,4,4,3,3,5,4,4,3
12/3/2025 10:52:49,22,Senior,Business administration,3.5,No,,5,3,3,5,3,4,1,1,2,4,1,1,2,4,2,4,4,5,3,2
12/3/2025 10:52:55,21,Senior,Health science,3.2,Yes,Baseball,2,3,2,4,3,1,3,4,1,4,2,5,2,2,4,4,4,3,3,4
12/3/2025 10:54:12,19,Freshman,Health sciences,NA,Yes,Baseball,4,4,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
12/3/2025 10:54:44,18,Freshman,Criminology,N/A,Yes,"Baseball & club",4,5,2,5,2,3,4,2,1,5,2,5,5,3,5,1,5,4,5,2
12/3/2025 10:57:22,21,Senior,Business Administration,3.5,Yes,Baseball,3,3,4,4,2,2,3,2,2,2,1,2,3,2,3,4,3,3,4,2
12/3/2025 10:59:49,21,Senior,Exercise science,3.2,Yes,Baseball,3,3,2,1,4,1,2,2,1,1,1,1,1,1,1,1,2,1,1,2
12/3/2025 11:01:38,20,Junior,Finance,3.3,Yes,Baseball,4,4,2,5,3,4,4,4,2,4,2,4,3,4,3,2,4,3,4,3
12/3/2025 11:45:57,20,Junior,Finance,3.3,No,,3,3,1,1,1,1,3,1,1,1,1,3,3,3,1,1,3,2,2,2
12/3/2025 11:52:39,19,Freshman,Finance,4,Yes,Baseball,5,5,5,5,4,3,3,3,3,5,2,4,1,4,2,3,4,3,3,3
12/3/2025 11:53:43,18,Freshman,Business Administration,3.6,Yes,Baseball,5,5,2,3,1,1,4,2,1,4,1,5,5,2,2,2,3,2,4,4"""

df = pd.read_csv(io.StringIO(data))

# Total IP score
q_cols = [col for col in df.columns if str(col).replace('.','').isdigit()]
df['IP_Score'] = df[q_cols].sum(axis=1)

# Group
df['Group'] = np.where(df['Major field of study'].str.contains('Computer Science', case=False), 'CS Seniors', 'Baseball Athletes')

# GPA numeric
df['GPA'] = pd.to_numeric(df['Overall GPA'], errors='coerce')

# Severity categories
def severity(score):
    if score <= 40: return 'Few'
    elif score <= 60: return 'Moderate'
    elif score <= 80: return 'Frequent'
    else: return 'Intense'
df['Severity'] = df['IP_Score'].apply(severity)

# ========= FIGURE 1 =========
plt.figure(figsize=(9,6))
plt.hist(df['IP_Score'], bins=10, edgecolor='black', color='#3498db')
plt.title('Figure 1. Distribution of Impostor Phenomenon Scores (n=28)', fontsize=14, fontweight='bold')
plt.xlabel('Total IP Score (20–100)'); plt.ylabel('Number of Participants')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout(); plt.savefig('Figure1_Histogram.png', dpi=300, bbox_inches='tight'); plt.close()

# ========= FIGURE 2 =========
valid = df.dropna(subset=['GPA'])
r, p = stats.pearsonr(valid['GPA'], valid['IP_Score'])
plt.figure(figsize=(9,6))
sns.regplot(x='GPA', y='IP_Score', data=valid, scatter_kws={'s':80})
plt.title(f'Figure 2. GPA vs Impostor Score (n=26)\nr = {r:.2f}, p = {p:.3f}', fontsize=14, fontweight='bold')
plt.xlabel('Overall GPA'); plt.ylabel('Total IP Score')
plt.tight_layout(); plt.savefig('Figure2_Scatter.png', dpi=300, bbox_inches='tight'); plt.close()

# ========= FIGURE 3 =========
means = df.groupby('Group')['IP_Score'].mean()
stds  = df.groupby('Group')['IP_Score'].std()
tstat, pval = stats.ttest_ind(df[df['Group']=='CS Seniors']['IP_Score'],
                              df[df['Group']=='Baseball Athletes']['IP_Score'], equal_var=False)
plt.figure(figsize=(8,6))
plt.bar(['Baseball Athletes','CS Seniors'], means, yerr=stds, capsize=10, color=['#3498db','#e67e22'])
plt.title(f'Figure 3. Mean IP Score by Group\nt = {tstat:.2f}, p = {pval:.3f}', fontsize=14, fontweight='bold')
plt.ylabel('Mean Total IP Score')
plt.tight_layout(); plt.savefig('Figure3_Means.png', dpi=300, bbox_inches='tight'); plt.close()

# ========= FIGURE 4 =========
plt.figure(figsize=(8,6))
sns.boxplot(x='Group', y='IP_Score', data=df, palette=['#3498db','#e67e22'])
plt.title('Figure 3. IP Score Distribution by Group', fontsize=14, fontweight='bold')
plt.ylabel('Total IP Score')
plt.tight_layout(); plt.savefig('Figure3_NEWBoxplot.png', dpi=300, bbox_inches='tight'); plt.close()

# ========= FIGURE 5 – Stacked Severity % =========
order = ['Few','Moderate','Frequent','Intense']
counts = pd.crosstab(df['Group'], df['Severity'])[order]
perc = counts.div(counts.sum(axis=1), axis=0) * 100
ax = perc.plot(kind='barh', stacked=True, figsize=(10,5), color=['#d5dbdb','#85c1e2','#3498db','#1a5276'])
plt.title('Figure 3. Impostor Severity Category by Group', fontsize=14, fontweight='bold')
plt.xlabel('Percentage of Participants (%)')
plt.legend(title='Severity', bbox_to_anchor=(1,1))
plt.tight_layout(); plt.savefig('Figure4_NEWSeverity.png', dpi=300, bbox_inches='tight'); plt.close()

# ========= FIGURE 6 – Top 5 Questions =========
means_q = df.groupby('Group')[q_cols].mean()
diff = means_q.loc['CS Seniors'] - means_q.loc['Baseball Athletes']
top5 = diff.abs().nlargest(5).index
top_diff = diff[top5]
plt.figure(figsize=(10,6))
top_diff.sort_values().plot(kind='barh', color='#e74c3c', alpha=0.8)
plt.title('Figure 5. Top 5 Questions Where CS Students Scored Higher', fontsize=14, fontweight='bold')
plt.xlabel('Mean Difference (CS − Athletes)')
for i, (q,v) in enumerate(top_diff.sort_values().items()):
    plt.text(v+0.02 if v>0 else v-0.02, i, f'{v:+.2f}', va='center', fontweight='bold')
plt.tight_layout(); plt.savefig('Figure5_NEWTopQuestions.png', dpi=300, bbox_inches='tight'); plt.close()

print("SUCCESS! All 6 figures created:")
print("→ Figure1_Histogram.png   Figure2_Scatter.png   Figure3_Means.png")
print("→ Figure4_Boxplot.png     Figure5_Severity.png  Figure6_TopQuestions.png")
print("Click the folder icon on the left → right-click each → Download")